version: '3.9'

services:
  mysql-m:
    container_name: hsa21-mysql-m
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql_m_data:/var/lib/mysql
      - ./mysql-m/my.cnf://etc/mysql/conf.d/my.cnf:ro
      - ./mysql-m/logs:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: hsa21
      MYSQL_USER: hsa21
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
  
  mysql-s1:
    container_name: hsa21-mysql-s1
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql_s1_data:/var/lib/mysql
      - ./mysql-s1/my.cnf://etc/mysql/conf.d/my.cnf:ro
      - ./mysql-s1/logs:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: hsa21
      MYSQL_USER: hsa21
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3307:3306
  
  mysql-s2:
    container_name: hsa21-mysql-s2
    image: mysql:8.3.0
    restart: always
    volumes:
      - mysql_s2_data:/var/lib/mysql
      - ./mysql-s2/my.cnf://etc/mysql/conf.d/my.cnf:ro
      - ./mysql-s2/logs:/var/log/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: hsa21
      MYSQL_USER: hsa21
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3308:3306

volumes:
  mysql_m_data:
    driver: local
  mysql_s1_data:
    driver: local
  mysql_s2_data:
    driver: local
